### ISSUE TITLE
Not compiling in windows wut rule missing.

### ISSUE THREAD

**Issue by Alexyo21** [WiiDatabase/Boot2vWii#1]
Hi, sorry for bothering you.
I think this project has an enormous potential, I'm just trying to compile it but I can't on windows says, the wut rule missing. And another thing I've made up an idea with this one. Can use te source code, if you don't mind ?

**Comment by Brawl345** [comment]
Sorry for the late reply, I haven't gotten a notification for this somehow.

Have you installed `wut` with dkp-pacman?

>And another thing I've made up an idea with this one. Can use te source code, if you don't mind ?

Sure, the source code is public domain.

**Comment by Alexyo21** [comment]
> Sorry for the late reply, I haven't gotten a notification for this somehow.
> 
> 
> 
> Have you installed `wut` with dkp-pacman?
> 
> 
> 
> >And another thing I've made up an idea with this one. Can use te source code, if you don't mind ?
> 
> 
> 
> Sure, the source code is public domain.( Thank you very much, I really appreciate it)

Good evening, and no worries 
I installed wut, but I understood that my laptop is the problem, cause always break the installation due to be incompatible with Linux and the driver that are always broken.
I'll try again tomorrow after another installation, I'll figure it out. I'll let you know if something wrong happens, but I highly doubt, because surely it's my laptop  problem that I can't fix.
Sorry for bothering you. 
Keep doing your work, it's a great idea.
Have a good evening.
Thanks a lot.

**Comment by Brawl345** [comment]
>cause always break the installation due to be incompatible with Linux and the driver that are always broken

I mean this: https://docs.microsoft.com/en-us/windows/wsl/install

**Comment by Alexyo21** [comment]
> >cause always break the installation due to be incompatible with Linux and the driver that are always broken
> 
> 
> 
> I mean this: https://docs.microsoft.com/en-us/windows/wsl/install

Oh right there is also that way, I'll try it, I never gave it a chance maybe. Thanks again.
