### ISSUE TITLE
[REQUEST] WiiU video mode changer integration

### ISSUE THREAD

**Issue by dracula99gr** [WiiDatabase/Boot2vWii#2]
Hello I have issues with my 40" 4K TV when loading the vWii because the WiiU does a poor job upscaling the image... It looks like 360p masked as 1080p... If I set wiiu resolution at 480p wii games on my TV look like I am playing on an emulator or something at higher resolution... So my TV definitely does better job upscaling the 480p vs the 1080p signal...

So some months ago I found [that solution](https://gbatemp.net/threads/hbl2hbc-v1-1-boot-from-wiiu-hbl-into-vwii-hbc.455673/post-9059814), a guy had intergraded into the hbl2hbc homebrew, so I used it whenever I wanted to load my vWii with all of my shortcuts.
He must have used [this code](https://github.com/FIX94/wiiu-video-mode-changer) for the 480p/720p/1080p mod that he created.
But that modded hbl2hbc isn't a viable solution anymore since the release of Aroma and Boot2vWii seems better overall... So I thought that it would be possible to integrate a feature to set vWii to 480p temporarily and when returning on wiiu the image would return to 1080p since it already has been done. That feature would be neat for my vWii picture quality and I would really appreciate the effort of even bothering to intergrate it...

Thank you so much for the development on the wiiu scene :) And thanks for your time! ♥

**Comment by cheatfreak47** [comment]
I'd like to second this request- the Wii U really does suck at upscaling vWii mode.
In the case of boot2vwii here, I'd imagine it'd best be implemented as a compile flag, much like DISPLAY currently is, and it should probably default to not doing anything if not specified.

**Comment by Brawl345** [comment]
I will gladly accept pull requests that implement this, but I won't work on it in the near future.

**Comment by killerpommes** [comment]
I tried to implement this. It works for me, i think :P 
But i am not a programmer so it might be all wrong or badly made. 
Also i took most of the code from [mives hbl2hbc mod](https://gbatemp.net/threads/hbl2hbc-v1-1-boot-from-wiiu-hbl-into-vwii-hbc.455673/page-11#post-9059814)

#https://github.com/killerpommes/Boot2vWii/tree/patch-1

**Comment by dracula99gr** [comment]
> I tried to implement this. It works for me, i think :P But i am not a programmer so it might be all wrong or badly made. Also i took most of the code from [mives hbl2hbc mod](https://gbatemp.net/threads/hbl2hbc-v1-1-boot-from-wiiu-hbl-into-vwii-hbc.455673/page-11#post-9059814)
> 
> #https://github.com/killerpommes/Boot2vWii/tree/patch-1

It works for me as well but it doesn't result to wuhb but to elf and rpx instead (rpx works fine it just doesn't have any icon splash etc)

EDIT: NVM for some reason it doesn't even customize the patches but it's defaulting to ConnectMii instead (the 480p patch & TV only seem to work fine tho) 
These are the instructions I wrote [Builds.txt](https://github.com/WiiDatabase/Boot2vWii/files/10366653/Builds.txt) please let me know if I missed something

**Comment by killerpommes** [comment]
It looks like you wrote "APPNAME not "APP_NAME". If the Pictures are missing, i would try relativ paths. Did you add wut and wut-tools to devkitpro? i think those are needed for the wuhb file.

**Comment by killerpommes** [comment]
> > I tried to implement this. It works for me, i think :P But i am not a programmer so it might be all wrong or badly made. Also i took most of the code from [mives hbl2hbc mod](https://gbatemp.net/threads/hbl2hbc-v1-1-boot-from-wiiu-hbl-into-vwii-hbc.455673/page-11#post-9059814)
> > #https://github.com/killerpommes/Boot2vWii/tree/patch-1
> 
> It works for me as well but it doesn't result to wuhb but to elf and rpx instead (rpx works fine it just doesn't have any icon splash etc)
> 
> EDIT: NVM for some reason it doesn't even customize the patches but it's defaulting to ConnectMii instead (the 480p patch & TV only seem to work fine tho) These are the instructions I wrote [Builds.txt](https://github.com/WiiDatabase/Boot2vWii/files/10366653/Builds.txt) please let me know if I missed something

It looks like you wrote "APPNAME not "APP_NAME". If the Pictures are missing, i would try relativ paths. Did you add wut and wut-tools to devkitpro? i think those are needed for the wuhb file.

**Comment by dracula99gr** [comment]
The pics are not missing i put them on these locations and yes I think I did add wut, wut-tools, devkitpro. Is there any way to check? I'm not sure if I added them correctly or if I added the latest version... (I'm using an Ubuntu based distro 22.04 to compile the wuhb files)
I tried to run them with the correct APP_NAME option 
![image](https://user-images.githubusercontent.com/20153526/211216401-722e1486-8e39-4e44-930c-d6906ccf8d17.png)
but it still doesn't have any customization neither it boots to the channel with that id but it boots on connectmii

**Comment by Brawl345** [comment]
The output has to look like this:

```
make TIDLOW=0x44574641 APP_NAME="WiiFlow" AUTHOR="Fledge68" ICON="assets/wiiflow.png"

main.c
linking ... Boot2vWii.elf
built ... Boot2vWii.rpx
Calculating metadata...
Updating sibling and child entries...
Populating data...
Writing header...
Writing /code/root.rpx...
Writing /meta/meta.ini...
Writing /meta/iconTex.tga.gz...
Writing dir_hash_table...
Writing dir_table...
Writing file_hash_table...
Writing file_table...
built ... Boot2vWii.wuhb
```

Dunno if the assets must be relative. Check that you have `wuhbtool` in your PATH. It's n $DEVKITPRO/tools/bin

**Comment by dracula99gr** [comment]
![image](https://user-images.githubusercontent.com/20153526/211223328-92f67966-fbd9-4133-9f30-e76eb1768c90.png)
It seems to be there

**Comment by dracula99gr** [comment]
OK so the `wuhbtool` path wasn't the issue but yes while the pictures weren't missing when I used relative paths it just worked the wuhb was generated successfully 
![image](https://user-images.githubusercontent.com/20153526/211937433-1e3b8f89-0e98-4fce-8f5a-14fd3b76f5bc.png)
BUT it still defaults to ConnectMii Channel no matter what i set for TIDLOW...
So that's my new [Builds.txt](https://github.com/WiiDatabase/Boot2vWii/files/10396633/Builds.txt)

**Comment by killerpommes** [comment]
Since i don't use linux and i do not program, i can not really help.
I can only say make sure you executed "make clean" after every build.
If that does not help try if it works when using not my fork.

**Comment by dracula99gr** [comment]
OK so `make clean` really did the trick this time! Everything works now BUT why doesn't it want to load WiiXplorer??! I triple checked the ID and all but it keeps returning me to Wii Menu....

PS: I also had issue with WiiFlowLite I had a typo on the ID (a 5 instead of 6) but that returned me immediately to Wii U menu not wii menu like WiiXplorer does wtf...

PS 2: Same behavior on Brawl345's code so I don't think your fork has anything to do with that

[Builds.txt](https://github.com/WiiDatabase/Boot2vWii/files/10415779/Builds.txt)

**Comment by Brawl345** [comment]
I have committed it to the feature/change-video-mode branch, would be great if someone can test this because I can't. Thanks @killerpommes for the patch, I tweaked it slightly to not use OS_DynLoad.

**Comment by dracula99gr** [comment]
Oh I just made a pull request sorry for the conflict!

I am going to test it right now!

**Comment by dracula99gr** [comment]
> I have committed it to the feature/change-video-mode branch, would be great if someone can test this because I can't. Thanks @killerpommes for the patch, I tweaked it slightly to not use OS_DynLoad.

Everything works! CTGPR, WiiFlowLite, WiiXplorer, ConnectMii and USBLoaderGX!
(I still ran make clean after each build)

**Comment by Brawl345** [comment]
Can you also confirm that the resolution changes correctly?

**Comment by dracula99gr** [comment]
I already have tried compiling it 720p and 480p and I had no issues the TV indicates 720p and 480p respectively
