### ISSUE TITLE
Boot2vWii seems broken somewhere, can't compile

### ISSUE THREAD

**Issue by DardelHMB** [WiiDatabase/Boot2vWii#6]
After running `make` I am hit with this:
```
filepathplaceholder/Boot2vWii-master/source/main.c: In function 'main':
<command-line>: error: expected expression before ':' token
filepathplaceholder/Boot2vWii-master/source/main.c:47:27: note: in expansion of macro 'DISPLAY'
   47 |     CMPTAcctSetScreenType(DISPLAY);
      |                           ^~~~~~~
make[1]: *** [/opt/devkitpro/devkitPPC/base_rules:21: main.o] Error 1
make: *** [Makefile:156: build] Error 2
```

I'm unsure what is causing this (if I was I would be opening up a pull request), other code compiles fine so I doubt its my devkitpro install.

**Comment by Brawl345** [comment]
This seems to be a problem with your devkitPro install. It works for me. Try updating and/or reinstalling devkitPro and make sure you have wut and wut-tools installed.

**Comment by DardelHMB** [comment]
My devkitPro seems fine, it's up to date and I have reinstalled it and wut/wut-tools so I'm unsure what the problem is
My distro is Linux Mint (ubuntu base) if thats relevant

**Comment by dominic-03** [comment]
Also running into the same issue, on Debian.

**Comment by TakuikaNinja** [comment]
It seems that `DISPLAY` doesn't get set to the default of `BOTH` when running make without any arguments. Explicitly setting it as an argument made it work for me.

**Comment by Brawl345** [comment]
It should though:
https://github.com/WiiDatabase/Boot2vWii/blob/master/source/main.c#L12-L14

**Comment by TakuikaNinja** [comment]
I know, but it doesn't get respected for some reason. I'm on EndeavourOS (Arch-based) and I have everything set up correctly afaik.

**Comment by Brawl345** [comment]
Sorry it took so long, this bug was REALLY hard to track down. It only happens on Linux systems with Xorg because Xorg sets the `$DISPLAY` variable and this conflicts with the one from Boot2vWii... that's why I couldn't reproduce it. "DISPLAY" is now named "DISPLAY_ON".
