### ISSUE TITLE
I can surf the Internet, but I can't download msys-2.10.0.7z, how can I fix this issue

### ISSUE THREAD

**Issue by ppddxda** [WiiDatabase/Boot2vWii#8]
I can surf the Internet, but I can't download msys-2.10.0.7z, how can I fix this
issue
![2024-12-17_102130](https://github.com/user-attachments/assets/2361b976-f72e-4d9e-8410-d2f3945bb999)
![2024-12-17_102426](https://github.com/user-attachments/assets/4cd7d1d3-ee00-4d94-bd19-34b11d941147)

**Comment by Brawl345** [comment]
Maybe some website is blocked in your country? I don't know how the devkitPro Updater works, this is also the wrong issue tracker. Try creating an issue there: https://github.com/devkitPro/installer/issues
